/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package compilers_project_2;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTDECL = 2;
  public int JJTVARIABLEDECL = 3;
  public int JJTVARIABLE = 4;
  public int JJTTYPE = 5;
  public int JJTTYPEPRIME = 6;
  public int JJTFUNCTIONDECL = 7;
  public int JJTFORMALS = 8;
  public int JJTVARIABLELIST = 9;
  public int JJTCLASSDECL = 10;
  public int JJTFIELDLIST = 11;
  public int JJTCLASSOPTIONS = 12;
  public int JJTIMPLEMENTSLIST = 13;
  public int JJTFIELD = 14;
  public int JJTINTERFACEDECL = 15;
  public int JJTPROTOTYPELIST = 16;
  public int JJTPROTOTYPE = 17;
  public int JJTSTMTBLOCK = 18;
  public int JJTVARIABLEDECLLIST = 19;
  public int JJTSTMTLIST = 20;
  public int JJTSTMT = 21;
  public int JJTIFSTMT = 22;
  public int JJTWHILESTMT = 23;
  public int JJTFORSTMT = 24;
  public int JJTBREAKSTMT = 25;
  public int JJTRETURNSTMT = 26;
  public int JJTPRINTSTMT = 27;
  public int JJTEXPRLIST = 28;
  public int JJTEXPR = 29;
  public int JJTEXPRPRIME = 30;
  public int JJTLVALUE = 31;
  public int JJTCALL = 32;
  public int JJTACTUALS = 33;
  public int JJTCONSTANT = 34;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "Decl",
    "VariableDecl",
    "Variable",
    "Type",
    "TypePrime",
    "FunctionDecl",
    "Formals",
    "VariableList",
    "ClassDecl",
    "FieldList",
    "ClassOptions",
    "ImplementsList",
    "Field",
    "InterfaceDecl",
    "PrototypeList",
    "Prototype",
    "StmtBlock",
    "VariableDeclList",
    "StmtList",
    "Stmt",
    "IfStmt",
    "WhileStmt",
    "ForStmt",
    "BreakStmt",
    "ReturnStmt",
    "PrintStmt",
    "ExprList",
    "Expr",
    "ExprPrime",
    "LValue",
    "Call",
    "Actuals",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=ddb0218219cf828490add824f7f6c3c6 (do not edit this line) */
