/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammar.java */
package compilers_project_2;

import java.io.FileNotFoundException;
import java.io.FileInputStream;

public class MyNewGrammar/*@bgen(jjtree)*/implements MyNewGrammarTreeConstants, MyNewGrammarConstants {/*@bgen(jjtree)*/
  protected static JJTMyNewGrammarState jjtree = new JJTMyNewGrammarState();
  // trie
  public Trie trie;

  static String tokenName[] = new String[1000];

  public static void main( String args [] ) throws ParseException
  {
tokenName[0] = "EOF"; tokenName[4] = "EOL";
        tokenName[5] = "_plus"; tokenName[6] = "_minus"; tokenName[7] = "_multiplication";
        tokenName[8] = "_division"; tokenName[9] = "_mod"; tokenName[10] = "_assignop";
        tokenName[11] = "_semicolon"; tokenName[12] = "_comma"; tokenName[13] = "_period";
        tokenName[14] = "_leftparen"; tokenName[15] = "_rightparen"; tokenName[16] = "_leftbracket";
        tokenName[17] = "_rightbracket"; tokenName[18] = "_leftbrace"; tokenName[19] = "_rightbrace";
        tokenName[20] = "_less"; tokenName[21] = "_lessequal"; tokenName[22] = "_greater";
        tokenName[23] = "_greaterequal"; tokenName[24] = "_equal"; tokenName[25] = "_notequal";
        tokenName[26] = "_and"; tokenName[27] = "_or"; tokenName[28] = "_not";
        tokenName[29] = "_boolean"; tokenName[30] = "_break"; tokenName[31] = "_class";
        tokenName[32] = "_double"; tokenName[33] = "_else"; tokenName[34] = "_extends";
        tokenName[35] = "_for"; tokenName[36] = "_if"; tokenName[37] = "_implements";
        tokenName[38] = "_int"; tokenName[39] = "_interface"; tokenName[40] = "_new";
        tokenName[41] = "_newarray"; tokenName[42] = "_null"; tokenName[43] = "_println";
        tokenName[44] = "_readln"; tokenName[45] = "_return"; tokenName[46] = "_string";
        tokenName[47] = "_void"; tokenName[48] = "_while"; tokenName[49] = "_booleanconstant";
        tokenName[50] = "_id"; tokenName[51] = "_intconstant"; tokenName[52] = "_doubleconstant";
        tokenName[53] = "_stringconstant"; tokenName[54] = "DIGIT"; tokenName[55] = "LETTER";
        tokenName[56] = "ALPHABET";

    MyNewGrammar parser = null;
    SimpleNode n;

    if ( args.length > 0 )
    {
                try
                {
                // We have a file to parse
                System.out.println( "file specified! Reading from file...\u005cn" );
                parser = new MyNewGrammar( new FileInputStream( args[0] ) );
                }
                catch ( FileNotFoundException e )
                {
                    // Specified file doesn't exist so don't go any further
                    System.out.println( "file not found! Terminating..." );
                    return;
                }
        }
        else
        {
                // Default to console input
                System.out.println( "No file specified! Reading from standard input...\u005cn" );
                parser = new MyNewGrammar( System.in );
        }

        try
        {
                n = MyNewGrammar.Start();
        n.dump("");
            parser.trie = new Trie();

        }
        catch ( Exception e )
        {
            System.out.println( "NOK." );
            System.out.println( e.getMessage() );
            parser.ReInit( System.in );
        }
        catch ( Error e )
        {
                System.out.println( "Oops." );
        System.out.println( e.getMessage() );
        }
  }

  static final public SimpleNode Start() throws ParseException {
    trace_call("Start");
    try {
 /*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Program();
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
    {if (true) return jjtn000;}
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    throw new Error("Missing return statement in function");
    } finally {
      trace_return("Start");
    }
  }

  static final public void Program() throws ParseException {
    trace_call("Program");
    try {
 /*@bgen(jjtree) Program */
  SimpleNode jjtn000 = new SimpleNode(JJTPROGRAM);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Decl();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _class:
        case _double:
        case _int:
        case _interface:
        case _string:
        case _void:
        case _id:
          Program();
          break;
        default:
          jj_la1[0] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Program");
    }
  }

  static final public void Decl() throws ParseException {
    trace_call("Decl");
    try {
 /*@bgen(jjtree) Decl */
  SimpleNode jjtn000 = new SimpleNode(JJTDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_1(3)) {
          VariableDecl();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _boolean:
          case _double:
          case _int:
          case _string:
          case _void:
          case _id:
            FunctionDecl();
            break;
          case _class:
            ClassDecl();
            break;
          case _interface:
            InterfaceDecl();
            break;
          default:
            jj_la1[1] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Decl");
    }
  }

  static final public void VariableDecl() throws ParseException {
    trace_call("VariableDecl");
    try {
 /*@bgen(jjtree) VariableDecl */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLEDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Variable();
        jj_consume_token(_semicolon);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("VariableDecl");
    }
  }

  static final public void Variable() throws ParseException {
    trace_call("Variable");
    try {
 /*@bgen(jjtree) Variable */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Type();
        jj_consume_token(_id);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Variable");
    }
  }

  static final public void Type() throws ParseException {
    trace_call("Type");
    try {
 /*@bgen(jjtree) Type */
  SimpleNode jjtn000 = new SimpleNode(JJTTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _int:
          jj_consume_token(_int);
          label_1:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _leftbracket:
              ;
              break;
            default:
              jj_la1[2] = jj_gen;
              break label_1;
            }
            jj_consume_token(_leftbracket);
            jj_consume_token(_rightbracket);
          }
          break;
        case _double:
          jj_consume_token(_double);
          label_2:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _leftbracket:
              ;
              break;
            default:
              jj_la1[3] = jj_gen;
              break label_2;
            }
            jj_consume_token(_leftbracket);
            jj_consume_token(_rightbracket);
          }
          break;
        case _boolean:
          jj_consume_token(_boolean);
          label_3:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _leftbracket:
              ;
              break;
            default:
              jj_la1[4] = jj_gen;
              break label_3;
            }
            jj_consume_token(_leftbracket);
            jj_consume_token(_rightbracket);
          }
          break;
        case _string:
          jj_consume_token(_string);
          label_4:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _leftbracket:
              ;
              break;
            default:
              jj_la1[5] = jj_gen;
              break label_4;
            }
            jj_consume_token(_leftbracket);
            jj_consume_token(_rightbracket);
          }
          break;
        case _id:
          jj_consume_token(_id);
          label_5:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _leftbracket:
              ;
              break;
            default:
              jj_la1[6] = jj_gen;
              break label_5;
            }
            jj_consume_token(_leftbracket);
            jj_consume_token(_rightbracket);
          }
          break;
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Type");
    }
  }

  static final public void FunctionDecl() throws ParseException {
    trace_call("FunctionDecl");
    try {
 /*@bgen(jjtree) FunctionDecl */
  SimpleNode jjtn000 = new SimpleNode(JJTFUNCTIONDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _id:
          Type();
          jj_consume_token(_id);
          jj_consume_token(_leftparen);
          Formals();
          jj_consume_token(_rightparen);
          StmtBlock();
          break;
        case _void:
          jj_consume_token(_void);
          jj_consume_token(_id);
          jj_consume_token(_leftparen);
          Formals();
          jj_consume_token(_rightparen);
          StmtBlock();
          break;
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("FunctionDecl");
    }
  }

  static final public void Formals() throws ParseException {
    trace_call("Formals");
    try {
 /*@bgen(jjtree) Formals */
  SimpleNode jjtn000 = new SimpleNode(JJTFORMALS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _id:
          VariableList();
          break;
        default:
          jj_la1[9] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Formals");
    }
  }

  static final public void VariableList() throws ParseException {
    trace_call("VariableList");
    try {
 /*@bgen(jjtree) VariableList */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLELIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Variable();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _comma:
          jj_consume_token(_comma);
          VariableList();
          break;
        default:
          jj_la1[10] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("VariableList");
    }
  }

  static final public void ClassDecl() throws ParseException {
    trace_call("ClassDecl");
    try {
 /*@bgen(jjtree) ClassDecl */
  SimpleNode jjtn000 = new SimpleNode(JJTCLASSDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_class);
        jj_consume_token(_id);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _extends:
          jj_consume_token(_extends);
          jj_consume_token(_id);
          break;
        default:
          jj_la1[11] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _implements:
          ImplementsList();
          break;
        default:
          jj_la1[12] = jj_gen;
          ;
        }
        jj_consume_token(_leftbrace);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _void:
        case _id:
          FieldList();
          break;
        default:
          jj_la1[13] = jj_gen;
          ;
        }
        jj_consume_token(_rightbrace);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ClassDecl");
    }
  }

  static final public void ImplementsList() throws ParseException {
    trace_call("ImplementsList");
    try {
 /*@bgen(jjtree) ImplementsList */
  SimpleNode jjtn000 = new SimpleNode(JJTIMPLEMENTSLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_implements);
        jj_consume_token(_id);
        label_6:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _comma:
            ;
            break;
          default:
            jj_la1[14] = jj_gen;
            break label_6;
          }
          jj_consume_token(_comma);
          jj_consume_token(_implements);
          jj_consume_token(_id);
        }
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ImplementsList");
    }
  }

  static final public void FieldList() throws ParseException {
    trace_call("FieldList");
    try {
 /*@bgen(jjtree) FieldList */
  SimpleNode jjtn000 = new SimpleNode(JJTFIELDLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Field();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _void:
        case _id:
          FieldList();
          break;
        default:
          jj_la1[15] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("FieldList");
    }
  }

  static final public void Field() throws ParseException {
    trace_call("Field");
    try {
 /*@bgen(jjtree) Field */
  SimpleNode jjtn000 = new SimpleNode(JJTFIELD);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_2(3)) {
          VariableDecl();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _boolean:
          case _double:
          case _int:
          case _string:
          case _void:
          case _id:
            FunctionDecl();
            break;
          default:
            jj_la1[16] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Field");
    }
  }

  static final public void InterfaceDecl() throws ParseException {
    trace_call("InterfaceDecl");
    try {
 /*@bgen(jjtree) InterfaceDecl */
  SimpleNode jjtn000 = new SimpleNode(JJTINTERFACEDECL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_interface);
        jj_consume_token(_id);
        jj_consume_token(_leftbrace);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _void:
        case _id:
          PrototypeList();
          break;
        default:
          jj_la1[17] = jj_gen;
          ;
        }
        jj_consume_token(_rightbrace);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("InterfaceDecl");
    }
  }

  static final public void PrototypeList() throws ParseException {
    trace_call("PrototypeList");
    try {
 /*@bgen(jjtree) PrototypeList */
  SimpleNode jjtn000 = new SimpleNode(JJTPROTOTYPELIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Prototype();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _void:
        case _id:
          PrototypeList();
          break;
        default:
          jj_la1[18] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("PrototypeList");
    }
  }

  static final public void Prototype() throws ParseException {
    trace_call("Prototype");
    try {
 /*@bgen(jjtree) Prototype */
  SimpleNode jjtn000 = new SimpleNode(JJTPROTOTYPE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _boolean:
        case _double:
        case _int:
        case _string:
        case _id:
          Type();
          jj_consume_token(_id);
          jj_consume_token(_leftparen);
          Formals();
          jj_consume_token(_rightparen);
          jj_consume_token(_semicolon);
          break;
        case _void:
          jj_consume_token(_void);
          jj_consume_token(_id);
          jj_consume_token(_leftparen);
          Formals();
          jj_consume_token(_rightparen);
          jj_consume_token(_semicolon);
          break;
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Prototype");
    }
  }

  static final public void StmtBlock() throws ParseException {
    trace_call("StmtBlock");
    try {
 /*@bgen(jjtree) StmtBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTSTMTBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_leftbrace);
        StmtBlockPrime();
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("StmtBlock");
    }
  }

  static final public void StmtBlockPrime() throws ParseException {
    trace_call("StmtBlockPrime");
    try {
 /*@bgen(jjtree) StmtBlockPrime */
  SimpleNode jjtn000 = new SimpleNode(JJTSTMTBLOCKPRIME);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_3(3)) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _minus:
          case _semicolon:
          case _leftparen:
          case _leftbrace:
          case _not:
          case _break:
          case _for:
          case _if:
          case _new:
          case _newarray:
          case _null:
          case _println:
          case _readln:
          case _return:
          case _while:
          case _booleanconstant:
          case _id:
          case _intconstant:
          case _doubleconstant:
          case _stringconstant:
            StmtList();
            break;
          default:
            jj_la1[20] = jj_gen;
            ;
          }
          jj_consume_token(_rightbrace);
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _boolean:
          case _double:
          case _int:
          case _string:
          case _id:
            VariableDeclList();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _minus:
            case _semicolon:
            case _leftparen:
            case _leftbrace:
            case _not:
            case _break:
            case _for:
            case _if:
            case _new:
            case _newarray:
            case _null:
            case _println:
            case _readln:
            case _return:
            case _while:
            case _booleanconstant:
            case _id:
            case _intconstant:
            case _doubleconstant:
            case _stringconstant:
              StmtList();
              break;
            default:
              jj_la1[21] = jj_gen;
              ;
            }
            jj_consume_token(_rightbrace);
            break;
          default:
            jj_la1[22] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("StmtBlockPrime");
    }
  }

  static final public void VariableDeclList() throws ParseException {
    trace_call("VariableDeclList");
    try {
 /*@bgen(jjtree) VariableDeclList */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLEDECLLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        VariableDecl();
        VariableDeclListPrime();
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("VariableDeclList");
    }
  }

  static final public void VariableDeclListPrime() throws ParseException {
    trace_call("VariableDeclListPrime");
    try {
 /*@bgen(jjtree) VariableDeclListPrime */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLEDECLLISTPRIME);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_4(2)) {
          VariableDeclList();
        } else {
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;

        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("VariableDeclListPrime");
    }
  }

  static final public void StmtList() throws ParseException {
    trace_call("StmtList");
    try {
 /*@bgen(jjtree) StmtList */
  SimpleNode jjtn000 = new SimpleNode(JJTSTMTLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Stmt();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _semicolon:
        case _leftparen:
        case _leftbrace:
        case _not:
        case _break:
        case _for:
        case _if:
        case _new:
        case _newarray:
        case _null:
        case _println:
        case _readln:
        case _return:
        case _while:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          StmtList();
          break;
        default:
          jj_la1[23] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("StmtList");
    }
  }

  static final public void Stmt() throws ParseException {
    trace_call("Stmt");
    try {
 /*@bgen(jjtree) Stmt */
  SimpleNode jjtn000 = new SimpleNode(JJTSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _semicolon:
        case _leftparen:
        case _not:
        case _new:
        case _newarray:
        case _null:
        case _readln:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _minus:
          case _leftparen:
          case _not:
          case _new:
          case _newarray:
          case _null:
          case _readln:
          case _booleanconstant:
          case _id:
          case _intconstant:
          case _doubleconstant:
          case _stringconstant:
            Expr();
            break;
          default:
            jj_la1[24] = jj_gen;
            ;
          }
          jj_consume_token(_semicolon);
          break;
        case _if:
          IfStmt();
          break;
        case _while:
          WhileStmt();
          break;
        case _for:
          ForStmt();
          break;
        case _break:
          BreakStmt();
          break;
        case _return:
          ReturnStmt();
          break;
        case _println:
          PrintStmt();
          break;
        case _leftbrace:
          StmtBlock();
          break;
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Stmt");
    }
  }

  static final public void IfStmt() throws ParseException {
    trace_call("IfStmt");
    try {
 /*@bgen(jjtree) IfStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTIFSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_if);
        jj_consume_token(_leftparen);
        Expr();
        jj_consume_token(_rightparen);
        Stmt();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _else:
          jj_consume_token(_else);
          Stmt();
          break;
        default:
          jj_la1[26] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("IfStmt");
    }
  }

  static final public void WhileStmt() throws ParseException {
    trace_call("WhileStmt");
    try {
 /*@bgen(jjtree) WhileStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTWHILESTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_while);
        jj_consume_token(_leftparen);
        Expr();
        jj_consume_token(_rightparen);
        Stmt();
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("WhileStmt");
    }
  }

  static final public void ForStmt() throws ParseException {
    trace_call("ForStmt");
    try {
 /*@bgen(jjtree) ForStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTFORSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_for);
        jj_consume_token(_leftparen);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _leftparen:
        case _not:
        case _new:
        case _newarray:
        case _null:
        case _readln:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          Expr();
          break;
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        jj_consume_token(_semicolon);
        Expr();
        jj_consume_token(_semicolon);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _leftparen:
        case _not:
        case _new:
        case _newarray:
        case _null:
        case _readln:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          Expr();
          break;
        default:
          jj_la1[28] = jj_gen;
          ;
        }
        jj_consume_token(_rightparen);
        Stmt();
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ForStmt");
    }
  }

  static final public void BreakStmt() throws ParseException {
    trace_call("BreakStmt");
    try {
 /*@bgen(jjtree) BreakStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTBREAKSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_break);
        jj_consume_token(_semicolon);
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("BreakStmt");
    }
  }

  static final public void ReturnStmt() throws ParseException {
    trace_call("ReturnStmt");
    try {
 /*@bgen(jjtree) ReturnStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTRETURNSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_return);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _leftparen:
        case _not:
        case _new:
        case _newarray:
        case _null:
        case _readln:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          Expr();
          break;
        default:
          jj_la1[29] = jj_gen;
          ;
        }
        jj_consume_token(_semicolon);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ReturnStmt");
    }
  }

  static final public void PrintStmt() throws ParseException {
    trace_call("PrintStmt");
    try {
 /*@bgen(jjtree) PrintStmt */
  SimpleNode jjtn000 = new SimpleNode(JJTPRINTSTMT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_println);
        jj_consume_token(_leftparen);
        ExprList();
        jj_consume_token(_rightparen);
        jj_consume_token(_semicolon);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("PrintStmt");
    }
  }

  static final public void ExprList() throws ParseException {
    trace_call("ExprList");
    try {
 /*@bgen(jjtree) ExprList */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRLIST);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        Expr();
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _comma:
          jj_consume_token(_comma);
          ExprList();
          break;
        default:
          jj_la1[30] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ExprList");
    }
  }

  static final public void Expr() throws ParseException {
    trace_call("Expr");
    try {
 /*@bgen(jjtree) Expr */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        if (jj_2_5(2147483647)) {
          Call();
          ExprPrime();
        } else {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _id:
            LValue();
            switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
            case _assignop:
              jj_consume_token(_assignop);
              Expr();
              break;
            default:
              jj_la1[31] = jj_gen;
              ;
            }
            ExprPrime();
            break;
          case _null:
          case _booleanconstant:
          case _intconstant:
          case _doubleconstant:
          case _stringconstant:
            Constant();
            ExprPrime();
            break;
          case _leftparen:
            jj_consume_token(_leftparen);
            Expr();
            jj_consume_token(_rightparen);
            ExprPrime();
            break;
          case _minus:
            jj_consume_token(_minus);
            Expr();
            ExprPrime();
            break;
          case _not:
            jj_consume_token(_not);
            Expr();
            ExprPrime();
            break;
          case _readln:
            jj_consume_token(_readln);
            jj_consume_token(_leftparen);
            jj_consume_token(_rightparen);
            ExprPrime();
            break;
          case _new:
            jj_consume_token(_new);
            jj_consume_token(_leftparen);
            jj_consume_token(_id);
            jj_consume_token(_rightparen);
            ExprPrime();
            break;
          case _newarray:
            jj_consume_token(_newarray);
            jj_consume_token(_leftparen);
            jj_consume_token(_intconstant);
            jj_consume_token(_comma);
            Type();
            jj_consume_token(_rightparen);
            ExprPrime();
            break;
          default:
            jj_la1[32] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Expr");
    }
  }

  static final public void ExprPrime() throws ParseException {
    trace_call("ExprPrime");
    try {
 /*@bgen(jjtree) ExprPrime */
  SimpleNode jjtn000 = new SimpleNode(JJTEXPRPRIME);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _plus:
          jj_consume_token(_plus);
          Expr();
          break;
        case _minus:
          jj_consume_token(_minus);
          Expr();
          break;
        case _multiplication:
          jj_consume_token(_multiplication);
          Expr();
          break;
        case _division:
          jj_consume_token(_division);
          Expr();
          break;
        case _mod:
          jj_consume_token(_mod);
          Expr();
          break;
        case _less:
          jj_consume_token(_less);
          Expr();
          break;
        case _lessequal:
          jj_consume_token(_lessequal);
          Expr();
          break;
        case _greater:
          jj_consume_token(_greater);
          Expr();
          break;
        case _greaterequal:
          jj_consume_token(_greaterequal);
          Expr();
          break;
        case _equal:
          jj_consume_token(_equal);
          Expr();
          break;
        case _notequal:
          jj_consume_token(_notequal);
          Expr();
          break;
        case _and:
          jj_consume_token(_and);
          Expr();
          break;
        case _or:
          jj_consume_token(_or);
          Expr();
          break;
        case _not:
          jj_consume_token(_not);
          Expr();
          break;
        default:
          jj_la1[33] = jj_gen;
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;

        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("ExprPrime");
    }
  }

  static final public void LValue() throws ParseException {
    trace_call("LValue");
    try {
 /*@bgen(jjtree) LValue */
  SimpleNode jjtn000 = new SimpleNode(JJTLVALUE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_id);
        label_7:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _period:
          case _leftbracket:
            ;
            break;
          default:
            jj_la1[34] = jj_gen;
            break label_7;
          }
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case _leftbracket:
            jj_consume_token(_leftbracket);
            Expr();
            jj_consume_token(_rightbracket);
            break;
          case _period:
            jj_consume_token(_period);
            jj_consume_token(_id);
            break;
          default:
            jj_la1[35] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("LValue");
    }
  }

  static final public void Call() throws ParseException {
    trace_call("Call");
    try {
 /*@bgen(jjtree) Call */
  SimpleNode jjtn000 = new SimpleNode(JJTCALL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        jj_consume_token(_id);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _period:
          jj_consume_token(_period);
          jj_consume_token(_id);
          break;
        default:
          jj_la1[36] = jj_gen;
          ;
        }
        jj_consume_token(_leftparen);
        Actuals();
        jj_consume_token(_rightparen);
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Call");
    }
  }

  static final public void Actuals() throws ParseException {
    trace_call("Actuals");
    try {
 /*@bgen(jjtree) Actuals */
  SimpleNode jjtn000 = new SimpleNode(JJTACTUALS);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _minus:
        case _leftparen:
        case _not:
        case _new:
        case _newarray:
        case _null:
        case _readln:
        case _booleanconstant:
        case _id:
        case _intconstant:
        case _doubleconstant:
        case _stringconstant:
          ExprList();
          break;
        default:
          jj_la1[37] = jj_gen;
          ;
        }
      } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Actuals");
    }
  }

  static final public void Constant() throws ParseException {
    trace_call("Constant");
    try {
 /*@bgen(jjtree) Constant */
  SimpleNode jjtn000 = new SimpleNode(JJTCONSTANT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
      try {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case _intconstant:
          jj_consume_token(_intconstant);
          break;
        case _doubleconstant:
          jj_consume_token(_doubleconstant);
          break;
        case _stringconstant:
          jj_consume_token(_stringconstant);
          break;
        case _booleanconstant:
          jj_consume_token(_booleanconstant);
          break;
        case _null:
          jj_consume_token(_null);
          break;
        default:
          jj_la1[38] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
      }
    } finally {
      trace_return("Constant");
    }
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_3R_22() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) jj_scanpos = xsp;
    if (jj_scan_token(_semicolon)) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) {
    jj_scanpos = xsp;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_3R_15()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_16()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3R_83() {
    if (jj_scan_token(_period)) return true;
    if (jj_scan_token(_id)) return true;
    return false;
  }

  static private boolean jj_3R_10() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_9() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_3R_10()) return true;
    return false;
  }

  static private boolean jj_3_3() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_9()) jj_scanpos = xsp;
    if (jj_scan_token(_rightbrace)) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) return true;
    }
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_scan_token(_leftbrace)) return true;
    if (jj_3R_47()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(51)) {
    jj_scanpos = xsp;
    if (jj_scan_token(52)) {
    jj_scanpos = xsp;
    if (jj_scan_token(53)) {
    jj_scanpos = xsp;
    if (jj_scan_token(49)) {
    jj_scanpos = xsp;
    if (jj_scan_token(42)) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    if (jj_scan_token(_period)) return true;
    if (jj_scan_token(_id)) return true;
    return false;
  }

  static private boolean jj_3R_81() {
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_81()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_82() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) return true;
    }
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_scan_token(_id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_63()) jj_scanpos = xsp;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_3R_64()) return true;
    if (jj_scan_token(_rightparen)) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_scan_token(_id)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_65()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_80() {
    return false;
  }

  static private boolean jj_3R_79() {
    if (jj_scan_token(_not)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_scan_token(_or)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_scan_token(_and)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_76() {
    if (jj_scan_token(_notequal)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_scan_token(_rightbracket)) return true;
    return false;
  }

  static private boolean jj_3R_32() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_scan_token(_rightbracket)) return true;
    return false;
  }

  static private boolean jj_3R_11() {
    if (jj_scan_token(_period)) return true;
    if (jj_scan_token(_id)) return true;
    if (jj_scan_token(_leftparen)) return true;
    return false;
  }

  static private boolean jj_3R_75() {
    if (jj_scan_token(_equal)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_scan_token(_rightbracket)) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_scan_token(_rightbracket)) return true;
    return false;
  }

  static private boolean jj_3R_74() {
    if (jj_scan_token(_greaterequal)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_scan_token(_leftbracket)) return true;
    if (jj_scan_token(_rightbracket)) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    if (jj_scan_token(_greater)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(_lessequal)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_scan_token(_less)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(_id)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_34()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_scan_token(_mod)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(_string)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_33()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(_boolean)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_32()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_scan_token(_division)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(_double)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_17()) {
    jj_scanpos = xsp;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) return true;
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(_int)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_30()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_scan_token(_multiplication)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_scan_token(_minus)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) {
    jj_scanpos = xsp;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) {
    jj_scanpos = xsp;
    if (jj_3R_74()) {
    jj_scanpos = xsp;
    if (jj_3R_75()) {
    jj_scanpos = xsp;
    if (jj_3R_76()) {
    jj_scanpos = xsp;
    if (jj_3R_77()) {
    jj_scanpos = xsp;
    if (jj_3R_78()) {
    jj_scanpos = xsp;
    if (jj_3R_79()) {
    jj_scanpos = xsp;
    if (jj_3R_80()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_66() {
    if (jj_scan_token(_plus)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_14()) return true;
    if (jj_scan_token(_id)) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(_newarray)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_scan_token(_intconstant)) return true;
    return false;
  }

  static private boolean jj_3R_8() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(_semicolon)) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_scan_token(_new)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_scan_token(_id)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_scan_token(_assignop)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_scan_token(_readln)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_scan_token(_rightparen)) return true;
    return false;
  }

  static private boolean jj_3_5() {
    if (jj_scan_token(_id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(14)) {
    jj_scanpos = xsp;
    if (jj_3R_11()) return true;
    }
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_scan_token(_not)) return true;
    if (jj_3R_43()) return true;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_scan_token(_minus)) return true;
    if (jj_3R_43()) return true;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_scan_token(_leftparen)) return true;
    if (jj_3R_43()) return true;
    if (jj_scan_token(_rightparen)) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_3R_8()) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_3R_62()) return true;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_3R_59()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_60()) jj_scanpos = xsp;
    if (jj_3R_61()) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_3R_58()) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(_println)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_scan_token(_return)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_45()) jj_scanpos = xsp;
    if (jj_scan_token(_semicolon)) return true;
    return false;
  }

  static private boolean jj_3R_39() {
    if (jj_scan_token(_break)) return true;
    if (jj_scan_token(_semicolon)) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_scan_token(_for)) return true;
    if (jj_scan_token(_leftparen)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_44()) jj_scanpos = xsp;
    if (jj_scan_token(_semicolon)) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    if (jj_scan_token(_while)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_36() {
    if (jj_scan_token(_if)) return true;
    if (jj_scan_token(_leftparen)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_3R_42()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_3R_41()) return true;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_3R_40()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public MyNewGrammarTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[39];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xa0000000,0xa0000000,0x10000,0x10000,0x10000,0x10000,0x10000,0x20000000,0x20000000,0x20000000,0x1000,0x0,0x0,0x20000000,0x1000,0x20000000,0x20000000,0x20000000,0x20000000,0x20000000,0x50044840,0x50044840,0x20000000,0x50044840,0x10004040,0x50044840,0x0,0x10004040,0x10004040,0x10004040,0x1000,0x400,0x10004040,0x1ff003e0,0x12000,0x12000,0x2000,0x10004040,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x4c0c1,0x4c0c1,0x0,0x0,0x0,0x0,0x0,0x44041,0x4c041,0x44041,0x0,0x4,0x20,0x4c041,0x0,0x4c041,0x4c041,0x4c041,0x4c041,0x4c041,0x3f3f18,0x3f3f18,0x44041,0x3f3f18,0x3e1700,0x3f3f18,0x2,0x3e1700,0x3e1700,0x3e1700,0x0,0x0,0x3e1700,0x0,0x0,0x0,0x0,0x3e1700,0x3a0400,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[5];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MyNewGrammar(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MyNewGrammar(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MyNewGrammar(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new MyNewGrammarTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MyNewGrammar(MyNewGrammarTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MyNewGrammarTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 39; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      trace_token(token, "");
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
      trace_token(token, " (in getNextToken)");
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[61];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 39; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 61; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static private int trace_indent = 0;
  static private boolean trace_enabled = true;

/** Enable tracing. */
  static final public void enable_tracing() {
    trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
    trace_enabled = false;
  }

  static private void trace_call(String s) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Call:   " + s);
    }
    trace_indent = trace_indent + 2;
  }

  static private void trace_return(String s) {
    trace_indent = trace_indent - 2;
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.println("Return: " + s);
    }
  }

  static private void trace_token(Token t, String where) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Consumed token: <" + tokenImage[t.kind]);
      if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
        System.out.print(": \"" + t.image + "\"");
      }
      System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
    }
  }

  static private void trace_scan(Token t1, int t2) {
    if (trace_enabled) {
      for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
      System.out.print("Visited token: <" + tokenImage[t1.kind]);
      if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
        System.out.print(": \"" + t1.image + "\"");
      }
      System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
    }
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 5; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
